CREATE TABLE IF NOT EXISTS public.products
(
    product_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text                                NOT NULL,
    description text                                NOT NULL,
    price       DECIMAL(10, 2)                      NOT NULL,
    popularity  INT                                 NOT NULL,
    image_url   text,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  text                                NOT NULL,
    updated_at  TIMESTAMP                       DEFAULT NULL,
    updated_by  text                            DEFAULT NULL
    );
ALTER TABLE IF EXISTS public.products OWNER to dark;

CREATE TABLE IF NOT EXISTS public.contacts
(
    contact_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text                                NOT NULL,
    email         text                                NOT NULL,
    mobile_number text                                NOT NULL,
    message       text                                NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    text                                NOT NULL,
    updated_at    TIMESTAMP                       DEFAULT NULL,
    updated_by    text                            DEFAULT NULL
);
ALTER TABLE IF EXISTS public.contacts OWNER to dark;