CREATE TABLE IF NOT EXISTS public.customers
(
    customer_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          text                                NOT NULL,
    email         text                                NOT NULL UNIQUE,
    mobile_number text                                NOT NULL,
    password_hash text                                NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    text                                NOT NULL,
    updated_at    TIMESTAMP DEFAULT NULL,
    updated_by    text      DEFAULT NULL,
    CONSTRAINT customers_uniq_email UNIQUE (email),
    CONSTRAINT customers_uniq_mobile_number UNIQUE (mobile_number)
);
ALTER TABLE IF EXISTS public.customers OWNER to dark;

CREATE TABLE IF NOT EXISTS public.address
(
    address_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT                              NOT NULL UNIQUE,
    street      text                                NOT NULL,
    city        text                                NOT NULL,
    state       text                                NOT NULL,
    postal_code text                                NOT NULL,
    country     text                                NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  text                                NOT NULL,
    updated_at  TIMESTAMP                       DEFAULT NULL,
    updated_by  text                            DEFAULT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE
);
ALTER TABLE IF EXISTS public.address OWNER to dark;