CREATE TABLE IF NOT EXISTS roles
(
    role_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT                              NOT NULL,
    name        text                                NOT NULL,
    created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by  text                                NOT NULL,
    updated_at  TIMESTAMP                       DEFAULT NULL,
    updated_by  text                            DEFAULT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id) ON DELETE CASCADE
);

INSERT INTO roles (customer_id, name, created_at, created_by)
VALUES (1, 'ROLE_ADMIN', CURRENT_TIMESTAMP, 'Anonymous user');