CREATE TABLE IF NOT EXISTS public.roles
(
    role_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       text                                NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by text                                NOT NULL,
    updated_at TIMESTAMP DEFAULT NULL,
    updated_by text      DEFAULT NULL,
    CONSTRAINT roles_uniq_name UNIQUE (name)
);
ALTER TABLE IF EXISTS public.roles OWNER to dark;

CREATE TABLE IF NOT EXISTS public.customers_roles
(
    customer_id BIGINT NOT NULL,
    role_id     BIGINT NOT NULL,
    PRIMARY KEY (customer_id, role_id),
    FOREIGN KEY (customer_id) REFERENCES public.customers (customer_id) ON DELETE CASCADE,
    FOREIGN KEY (role_id) REFERENCES public.roles (role_id) ON DELETE CASCADE
);
ALTER TABLE IF EXISTS public.customers_roles OWNER to dark;

INSERT INTO roles (name, created_at, created_by)
VALUES ('ROLE_USER', CURRENT_TIMESTAMP, 'DBA');

INSERT INTO roles (name, created_at, created_by)
VALUES ('ROLE_ADMIN', CURRENT_TIMESTAMP, 'DBA');

INSERT INTO roles (name, created_at, created_by)
VALUES ('ROLE_OPS_ENG', CURRENT_TIMESTAMP, 'DBA');
