CREATE TABLE IF NOT EXISTS orders
(
    order_id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id    BIGINT                              NOT NULL,
    total_price    DECIMAL(10, 2)                      NOT NULL,
    payment_id     text                                NOT NULL,
    payment_status text                                NOT NULL,
    order_status   text                                NOT NULL,
    created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by     text                                NOT NULL,
    updated_at     TIMESTAMP DEFAULT NULL,
    updated_by     text      DEFAULT NULL,
    FOREIGN KEY (customer_id) REFERENCES customers (customer_id)
);

CREATE TABLE IF NOT EXISTS order_items
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id      BIGINT                              NOT NULL,
    product_id    BIGINT                              NOT NULL,
    quantity      INT                                 NOT NULL,
    price         DECIMAL(10, 2)                      NOT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    created_by    text                                NOT NULL,
    updated_at    TIMESTAMP DEFAULT NULL,
    updated_by    text      DEFAULT NULL,
    FOREIGN KEY (order_id) REFERENCES orders (order_id),
    FOREIGN KEY (product_id) REFERENCES products (product_id)
);